### ISSUE TITLE
Unexpected (and unwanted) JPEG scaling

### ISSUE THREAD

**Issue by 224XS** [MissEmlizB/Annotate-ML#1]
Great Job!  I like this app.  Tried to create a data set for Turi Create and found an issue.
Exported files have all coordinates scaled which shrinks and moved them relative to origin.
In tracing through your code, in AddPhotos in Document.swift:
```
 guard let data = image.tiffRepresentation,
					let image = NSImage(data: data) else {
					continue
				}
```
It takes an image file which both Preview and Photoshop is, say 1024 x 800, and the  resulting image from the NSImage call is about a third the size(when original resolution is 240 dpi). The scale factor is different for each input image. I suspect it has to do with differing image resolution among images.

**Comment by MissEmlizB** [comment]
Hi! Thanks for using the app! Could you share some photos that can replicate this behaviour?

**Comment by 224XS** [comment]
Thanks for response!
I’m driving at the moment, but when I get back to office tonight, i will shoot you some examples 
Ira

**Comment by 224XS** [comment]
OK, here we go

First, an original jpg, annotated in ML-Annotate





Next, a screen shot of my Jupiter note book, exploring ground truth
After :    dataj['image_with_ground_truth'] =  tc.object_detector.util.draw_bounding_boxes(dataj['image'], dataj['annotations'])



For reference, the true fun column width in the original jpg is roughly 80 pixels, if you look at the the annotation column above, you can
The widths averaging about 23-24px. Also the scaling shifts alll the bounding boxes up and to the left.

Finally, here is the original jpg, should you wish to try it out



Thanks in advance for the help!


Ira

**Comment by MissEmlizB** [comment]
Hi again! I seem to be having trouble seeing your photos. Can you upload them again somewhere so that I could see them?

![The curious case of the missing file attachments](https://i.ibb.co/JjxdD95/Screenshot-2020-07-06-at-09-09-55.png)

**Comment by 224XS** [comment]
Good Morning!
It seems the GitHub  messaging system does not pass along enclosures. I set up a shared album on iCloud with the pix. I’ll get the url in a few minutes
Ira

**Comment by 224XS** [comment]
Here you go:

https://www.icloud.com/sharedalbum/#B0fGrq0zwGDLc2q

**Comment by MissEmlizB** [comment]
Thanks for sharing them! 
Sorry for responding a bit late! 😅

I think I found what's causing the 'scaling' issue. I changed AnnotationsView to prioritise the photo's actual size.

![NSImageRep to the rescue!](https://i.ibb.co/X3bdwpb/Screenshot-2020-07-06-at-20-11-38.png)
![Yay, it shows the real size now!](https://i.ibb.co/609ychy/Screenshot-2020-07-06-at-20-12-51.png)

(I just need to figure out what's causing that offset...)

![I think it looks better now?](https://i.ibb.co/hDsVy0V/Screenshot-2020-07-06-at-20-19-54.png)

**Comment by 224XS** [comment]
Many thanks Emily!
Strong work!
Are you planning to pull the new revision?
Ira

**Comment by 224XS** [comment]
FWIW, the offset seems constant, not proportional. I tried briefly digging into your code for this but came up empty. I do really appreciate your help here! Your annotation tool goes way beyond what other tools offer in terms of features and friendly UI!

Ira

**Comment by MissEmlizB** [comment]
I think it's okay now! But just to be sure, can you check if [this](https://github.com/MissEmlizB/Annotate-ML/tree/turi-create-export) works correctly?
